#+TITLE: Emacs Configuration
#+AUTHOR: Alex Lu
#+EMAIL: alexluigit@gmail.com
#+PROPERTY: header-args :mkdirp yes
#+OPTIONS: auto-id:t

* Overview
:PROPERTIES:
:CUSTOM_ID: Overview-e0bb5308
:END:
** About
:PROPERTIES:
:CUSTOM_ID: Overview-About-69b700f5
:END:

This project is my emacs configuration.

*** Structure
:PROPERTIES:
:CUSTOM_ID: Overview-About-Structure-72aebf03
:END:

+ Init file (init.el / early-init.el)
+ Optimization options (early-optimize.el)
+ Core libraries (core/*, core/autoload/*)
+ extensions (lisp/*)
+ Main config file (ale.org)

doc

#+begin_src emacs-lisp :tangle (ale-minimal-config)
;;; minimal.el --- -*- lexical-binding: t -*-
#+end_src

#+begin_src emacs-lisp
;;; full.el --- -*- lexical-binding: t -*-
#+end_src

*** COPYING
:PROPERTIES:
:CUSTOM_ID: Overview-About-COPYING-f36578ea
:END:

Copyright (c) 2020-2021  Alex Lu <alexluigit@gmail.com>

This file is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at
your option) any later version.

This file is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this file.  If not, see <http://www.gnu.org/licenses/>.

** Quickstart
:PROPERTIES:
:CUSTOM_ID: Overview-Quickstart-5f7409ee
:END:
*** Dependencies
:PROPERTIES:
:CUSTOM_ID: Overview-Quickstart-Dependencies-fd1eaa61
:END:

required:
fd
rg
git
exa
fish
mailcap
words
noto-fonts-emoji
z

optional:
sarasa-gothic
victor-mono-nerd-font
xdotool

*** Install
:PROPERTIES:
:CUSTOM_ID: Overview-Quickstart-Install-d1b7b6a4
:END:

This section contails instructions on how to use this config.

- Make sure to backup your own emacs config before installation.

#+begin_src shell :tangle no
cp -r ~/.emacs.d ~/.emacs.d.bak
#+end_src

- Clone the repo and tangle the config.

#+begin_src shell :tangle no
git clone https://www.github.com/alexluigit/emacs-grandview
# either put it to ~/.emacs.d
mv ~/emacs-grandview ~/.emacs.d
# or conform XDG spec
mv ~/emacs-grandview ~/.config/emacs/
# or use symlink
mv ~/emacs-grandview ~/Code/emacs-grandview
ln -sf ~/Code/emacs-grandview ~/.config/emacs

# Tangle the config
emacs --daemon
emacsclient -e '(kill-emacs)'
#+end_src

** Restart script
:PROPERTIES:
:CUSTOM_ID: Overview-Restart_script-15fa833f
:END:

Script for starting up emacs.

+ *Why this bash script?*

  Emacs is a single-threaded program, so if it hangs, we can not
  expect it to evaluate any elisp code.

+ *What does this script do?*

  If this org file get modified, =ale-init-build= function will tangle
  this file.  After the build function finishes, it kill current emacs
  and open emacs with new init file.

  Since =ale-init-build= function is added to =kill-emacs-hook=, emacs
  main process only get killed after the tangle function finishes
  (unless we use '-9' flag in kill command).  In my case, it usually
  takes emacs less than 1s to tangle this org file, so if emacs main
  process keep alive for over 3s after *killall emacs* command, it
  probably means emacs get frozen, so we just kill it with *kill -9*.

+ *How to use this script?*

  You don't need to install this script if you have followed
  =Installation= section. This script will be tangled to
  *~/.local/share/em*, so if you want to get access to =em restart= command from
  terminal, make sure *~/.local/bin/em* is in your *$PATH* environment
  variable.

Here is the content of the script.

#+begin_src bash :tangle "~/.local/bin/em" :shebang "#!/usr/bin/env bash"
restart () {
  notify-send "Restarting emacs..." 2>/dev/null
  emacs_pid=$(pidof emacs)
  timeout=300
  counter=0
  killall emacs
  while $(kill -0 $emacs_pid 2>/dev/null) && [[ $counter -lt $timeout ]]; do
    counter=$((counter + 1))
    sleep 0.01
  done
  kill -9 $emacs_pid 2>/dev/null
  rm -rf ~/.config/emacs/eln-cache 2>/dev/null
  [[ $1 == "-p" ]] && rm -rf ~/.cache/emacs/{straight/build,eln} 2>/dev/null
  [[ $1 == "-r" ]] && rm -rf ~/.cache/emacs/ale 2>/dev/null
  [[ $1 == "-R" ]] && rm -rf ~/.cache/emacs/{ale,straight,eln} 2>/dev/null
  emacs --daemon
  command -v xdotool >/dev/null 2>&1 && xdotool set_desktop 0
  emacsclient -cne '(delete-file "~/nohup.out")' >/dev/null 2>&1
}

open () { emacs -nw ${@}; }

[[ -z "$@" ]] || ! $(declare -f -F $1 >/dev/null 2>&1) && { open ${@:1}; exit 0; }
$1 ${@:2}
#+end_src

You can also restart emacs by invoking =restart-emacs= command inside
emacs (again, comfirm your $PATH environment variable).

#+begin_src emacs-lisp
(defun restart-emacs ()
  "A elisp wrapper to `em' command."
  (interactive)
  (let ((default-directory "~"))
    (start-process "" nil "nohup" "em" "restart")))
#+end_src

* *CORE CONFIGURATION*
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-f16a0fb4
:END:

Load core of emacs-grandview. It is *NOT* recommend to delete / comment out this section.

** Text editing
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Text_editing-137675b5
:END:
*** Modal editing
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Text_editing-Modal_editing-fa54405a
:END:

Unlike =evil-mode=, which tries to create a whole vim emulation in emacs, =meow=
only focus on bringing the goodness of modal editing to vanilla emacs.

You may noticed that I didn't include any keybindings of meow here, that's
because it can be very lengthy and should be configured separately, see
[[#*CORE_CONFIGURATION*-Keybindings-3cbb54be][Keybindings]] for details.

If you want to know more about meow or modal editing in general, check out [[https://www.github.com/DoglooksGood/meow][meow]].

#+begin_src emacs-lisp
(use-package meow
  :demand t
  :init (meow-global-mode)
  :config
  (advice-add 'meow--maybe-highlight-num-positions :override #'ignore)
  (advice-add 'meow-minibuffer-quit :override #'keyboard-escape-quit)
  (unless IS-GUI ; Terminal cursor shape
    (advice-add 'meow--update-cursor :after #'ale-set-cursor))
  (meow--thing-register 'tag #'ale--inner-of-tag #'ale--bounds-of-tag)
  (meow-setup-line-number)
  (define-key meow-motion-state-keymap (kbd ale-local-leader-key) meow-leader-keymap)
  (define-key meow-motion-state-keymap
    (kbd (concat ale-local-leader-key " " ale-local-leader-key)) 'switch-to-buffer)
  (setq meow-visit-sanitize-completion nil)
  (setq meow-use-clipboard t)
  (setq meow-esc-delay 0.001)
  (setq meow-keypad-describe-delay 0.5)
  (setq meow-select-on-change t)
  (setq meow-cursor-type-normal 'box)
  (setq meow-cursor-type-insert '(bar . 4))
  (setq meow-cursor-type-default 'hbar)
  (setq meow-selection-command-fallback
        '((meow-replace . meow-yank)
          (meow-reverse . back-to-indentation)
          (meow-change . meow-change-char)
          (ale-save . ale-pulse-save-line)
          (meow-kill . ale-kill-whole-line)
          (meow-cancel . keyboard-quit)
          (meow-pop . meow-pop-grab)
          (meow-delete . meow-C-d)))
  (setq meow-char-thing-table
        '((?r . round)
          (?\[ . square)
          (?c . curly)
          (?s . string)
          (?e . symbol)
          (?w . window)
          (?b . buffer)
          (?p . paragraph)
          (?\^? . line)
          (?' . line)
          (?d . defun)
          (?i . indent)
          (?t . tag)
          (?x . extend)))
  (add-to-list 'meow-mode-state-list '(helpful-mode . normal)))
#+end_src

*** Symbol pairs
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Text_editing-Symbol_pairs-9a7ea7b5
:END:

=embrace.el= is a package for symbol pairs insert/change/delete which resembles
to =surround.vim= in vim.
I've forked this package to extract =embrace-default-pairs= out, so we can use
keys like ~,r~ to select an inner parenthesis block (this assumes your comma key
has been bound to =meow-inner-of-thing=.)

#+begin_src emacs-lisp
(use-package embrace
  :straight
  (embrace :type git :depth full :host github
           :repo "cute-jumper/embrace.el"
           :fork (:host github :repo "alexluigit/embrace.el"))
  :after-call meow--selection-type
  :init
  (setq embrace-default-pairs
        '((?r . ("(" . ")"))
          (?R . ("( " . " )"))
          (?c . ("{" . "}"))
          (?C . ("{ " . " }"))
          (?\[ . ("[" . "]"))
          (?\] . ("[ " . " ]"))
          (?a . ("<" . ">"))
          (?A . ("< " . " >"))
          (?s . ("\"" . "\""))
          (?\' . ("\'" . "\'"))
          (?` . ("`" . "`")))))
#+end_src

*** Paragraphs
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Text_editing-Paragraphs-ffa7838c
:END:

The =ale-fill.el= library is a tiny wrapper around some Emacs settings and modes
that are scrattered around several files, which control (i) how paragraphs or
comments in programming modes should be wrapped to a given column count, and
(ii) what constitutes a sentence. I put them all together here to make things
easier to track.  Use M-n and M-p for navigating between paragraphs.

=ale-fill-fill-mode= sets my desired default column width for all buffers, while
it applies another value for programming modes (in case there is a need to
control the two cases separately). Those values are stored in the variables
=ale-fill-default-column= and =ale-fill-prog-mode-column= respectively. My minor
mode also enables =auto-fill-mode= in text-mode and prog-mode buffers through
the appropriate hooks. Disabling =ale-fill-fill-mode= will remove all those
customisations.

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package paragraphs
  :straight (:type built-in)
  :bind
  ("M-n" . forward-paragraph)
  ("M-p" . backward-paragraph)
  :init
  (setq-default truncate-lines t)
  (ale-fill-fill-mode 1)
  :config
  (setq ale-fill-default-column 80)
  (setq ale-fill-prog-mode-column 100)
  (setq sentence-end-double-space t)
  (setq sentence-end-without-period nil)
  (setq colon-double-space nil)
  (setq use-hard-newlines nil)
  (setq adaptive-fill-mode t))
#+end_src

** Navigation
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Navigation-cd0d21c1
:END:

Settings for text/code/file navigation in emacs.
The relevent packages are:

+ *display-line-numbers*: Display line numbers when programming.
+ *better-jumper*: create a jump list (same concept in vim) in emacs.
+ *avy*: Jump to visible text.
+ *xref*: provides helpful commands for code navigation and discovery.

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package display-line-numbers
  :straight (:type built-in)
  :hook
  (prog-mode . display-line-numbers-mode))

(use-package better-jumper
  :after-call pre-command-hook
  :config
  (better-jumper-mode +1)
  (ale-jumper-sensible-jump-mode))

(use-package avy
  :config
  (setq avy-timeout-seconds 0.3)
  (setq avy-all-windows nil)
  (setq avy-keys '(?a ?r ?s ?t ?n ?e ?i ?o)))

(use-package xref
  :straight (:type built-in)
  :config
  (setq xref-show-definitions-function #'xref-show-definitions-completing-read)
  (setq xref-show-xrefs-function #'xref-show-definitions-completing-read)
  (setq xref-file-name-display 'project-relative)
  (setq xref-search-program 'ripgrep))
#+end_src

** Minibuffer
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Minibuffer-c81be95a
:END:

+ *minibuffer*: Basic minibuffer config.
+ *isearch-mb*: An alternative isearch UI.
+ *savehist*: Keeps a record of actions involving the minibuffer.

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package minibuffer
  :straight (:type built-in)
  :config
  (setq completion-category-defaults nil)
  (setq completion-cycle-threshold 3)
  (setq completion-flex-nospace nil)
  (setq completion-pcm-complete-word-inserts-delimiters t)
  (setq completion-pcm-word-delimiters "-_./:| ")
  (setq completion-show-help nil)
  (setq completion-auto-help nil)
  (setq completion-ignore-case t)
  (setq-default case-fold-search t)   ; For general regexp
  (setq read-buffer-completion-ignore-case t)
  (setq read-file-name-completion-ignore-case t)
  (setq enable-recursive-minibuffers t)
  (setq resize-mini-windows 'grow-only)
  (setq minibuffer-eldef-shorten-default t)
  (setq! minibuffer-prompt-properties '(read-only t cursor-intangible t face minibuffer-prompt))
  (minibuffer-depth-indicate-mode 1))

(use-package isearch-mb
  :after-call isearch-mode
  :config
  (isearch-mb-mode)
  (add-to-list 'isearch-mb--with-buffer #'consult-isearch)
  (add-to-list 'isearch-mb--after-exit #'anzu-isearch-query-replace)
  :bind
  (:map isearch-mb-minibuffer-map
        ([remap previous-matching-history-element] . consult-isearch)))

(use-package savehist
  :after-call minibuffer-setup-hook
  :straight (:type built-in)
  :config
  (setq savehist-file (locate-user-emacs-file "savehist"))
  (setq history-length 10000)
  (setq history-delete-duplicates t)
  (setq savehist-save-minibuffer-history t)
  (savehist-mode))
#+end_src

** Completion framework
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Completion_framework-af83619f
:END:

The optimal way of using Emacs is through searching and narrowing
selection candidates.  Spend less time worrying about where things are
on the screen and more on how fast you can bring them into focus.
This is, of course, a matter of realigning priorities, as we still
wish to control every aspect of the interface.

+ *vertico*

  A minimalistic completion UI.

+ *orderless*

  This package provides an `orderless' completion style that divides the pattern
  into components (space-separated by default), and matches candidates that
  match all of the components in any order.

+ *marginalia*
  This is a utility jointly developed by Daniel Mendler and Omar
  Antolín Camarena that provides annotations to completion
  candidates.  It is meant to be framework-agnostic, so it works with
  Selectrum, Icomplete, vertico, and Embark.

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package vertico
  :after-call pre-command-hook
  :config
  (set-face-attribute 'vertico-current nil :background
                      (face-attribute 'lazy-highlight :background nil t)
                      :weight 'semi-bold)
  (vertico-mode 1))

(use-package orderless
  :after-call minibuffer-setup-hook
  :config
  (setq completion-styles '(orderless))
  (setq orderless-component-separator " +")
  (setq orderless-matching-styles
        '(ale-pinyin-build-regexp-string
          orderless-initialism
          orderless-prefixes
          orderless-regexp))
  (setq orderless-style-dispatchers
        '(ale-orderless-literal-dispatcher
          ale-orderless-initialism-dispatcher
          ale-orderless-without-literal-dispatcher
          ale-orderless-pinyin-dispatcher)))

(use-package consult
  :after-call minibuffer-setup-hook
  :init
  (setq completion-in-region-function #'consult-completion-in-region)
  (setq register-preview-delay 0.2)
  (setq register-preview-function #'consult-register-format)
  (advice-add #'register-preview :override #'consult-register-window)
  (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)
  (advice-add #'switch-to-buffer :around #'ale-consult-switch-buffer-advisor)
  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref)
  :bind
  (:map ale-consult-map
        ("/" . consult-line-multi)
        ("e" . consult-compile-error)
        ("r" . consult-ripgrep)
        ("k" . consult-keep-lines)
        ("i" . consult-imenu-multi)
        ("f" . consult-focus-lines)
        ("n" . consult-outline)
        ("o" . consult-org-heading)
        ("R" . consult-register)
        ("y" . consult-yank-from-kill-ring)
        ("m" . consult-minor-mode-menu)
        ("c" . consult-complex-command)
        ("C" . consult-mode-command))
  :config
  (advice-add #'consult-line :around #'ale-consult-line-advisor)
  (setq consult-project-root-function #'ale-consult-project-root)
  (setq consult-line-numbers-widen t)
  (setq consult-async-min-input 3)
  (setq consult-async-input-debounce 0.5)
  (setq consult-async-input-throttle 0.8)
  (setq consult-narrow-key ">"))

(use-package embark
  :after-call dired-after-readin-hook minibuffer-setup-hook
  :bind
  (("C-." . embark-act)
   :map minibuffer-local-map ("C-." . embark-act) ("C-," . embark-become)
   :map embark-collect-mode-map ("C-." . embark-act))
  :config
  (use-package embark-consult :demand t)
  (ale-embark-keymaps 1)
  (setq embark-quit-after-action t)
  (setq embark-action-indicator
        (let ((act (propertize "Act" 'face 'success)))
          (cons act (concat act " on '%s'"))))
  (setq embark-become-indicator (propertize "Become" 'face 'warning)))

(use-package marginalia
  :after-call minibuffer-setup-hook
  :config
  (setq marginalia-annotators
        '(marginalia-annotators-heavy
          marginalia-annotators-light))
  (marginalia-mode))
#+end_src

** Viewport
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Viewport-e557b1b8
:END:

The =display-buffer-alist= is intended as a rule-set for controlling
the display of windows.  The objective is to create a more intuitive
workflow where targeted buffer groups or types are always shown in a
given location, on the premise that predictability improves usability.

For each buffer action in it we can define several functions for selecting the
appropriate window.  These are executed in sequence, but my usage thus far
suggests that a simpler method is just as effective for my case.

Additionally, I've set =split-height-threshold= to nil and =split-width-threshold=
to 0 to ensure every new window will open in horizontal split.

=ale-modeline-mode= provides following infos in modeline:
- Meow current state (INSERT/NORMAL...)
- Filename
- Current line / column
- Total lines
- Git branch
- Progress bar of current document
Its source code lies in *autoload/modeline.el*

+ *ace-window*: Index based window motions

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package window
  :straight (:type built-in)
  :config
  (setq display-buffer-alist
        `(("\\*\\(Flymake\\|Messages\\|Backtrace\\|Warnings\\|Compile-Log\\|Custom\\)\\*"
           (display-buffer-in-side-window)
           (window-height . 0.2)
           (side . top))
          ("^\\*\\(Help\\|helpful\\).*"
           (display-buffer-in-side-window)
           (window-width . 0.4)
           (side . right))
          ("\\*\\vc-\\(incoming\\|outgoing\\|Output\\|Register Preview\\).*"
           (display-buffer-at-bottom))))
  (setq help-window-select t)
  (setq window-combination-resize t)
  (setq even-window-sizes 'height-only)
  (setq window-sides-vertical nil)
  (setq switch-to-buffer-in-dedicated-window 'pop)
  (setq split-height-threshold nil)
  (setq split-width-threshold 0))

(use-package ace-window
  :config
  (setq aw-keys '(?a ?r ?s ?t ?n ?e ?i ?o)))

(ale-frame-enable 'fringe-mode)
(ale-frame-enable 'ale-window-recenter-mode)
(ale-frame-enable 'ale-pulse-advice-commands-mode)
(ale-frame-enable 'ale-font-setup)
(ale-frame-enable 'ale-opacity-auto-mode)
(ale-modeline-mode)
#+end_src

** User interface
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-User_interface-479a9238
:END:

Basic user interface settings.

The relevent packages are:

+ *all-the-icons*: icons library.
+ *anzu*: interactive query replace.
+ *transient*: a built-in package in emacs 28 for "transient" commands.

=modus-vivendi= is a built-in theme in emacs (version >= 28) created by Protesilaos Stavrou.

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package all-the-icons
  :init
  (unless (file-exists-p "~/.local/share/fonts/all-the-icons.ttf")
    (all-the-icons-install-fonts)))

(use-package transient
  :after-call pre-command-hook
  :straight (:type built-in)
  :config
  (setq transient-show-popup -0.5)
  (transient-bind-q-to-quit)
  :bind
  ((:map transient-map
         ("<escape>" . transient-quit-all))
   (:map transient-sticky-map
         ("ESC" . transient-quit-all))))

(use-package anzu
  :after-call isearch-mode
  :config
  (global-anzu-mode +1))

(use-package custom
  :straight (:type built-in)
  :init
  (setq modus-themes-links 'no-underline)
  :hook (emacs-startup . (lambda () (load-theme 'modus-vivendi))))
#+end_src

** Keybindings
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Keybindings-3cbb54be
:END:

This section contains all core keybindings of emacs-grandview.

*** INSERT
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Keybindings-INSERT-0190d698
:END:

#+begin_src emacs-lisp
(bind-keys
 :map meow-insert-state-keymap
 ("<escape>" . ale-escape)
 ("C-u" . ale-kill-whole-line)
 ("<C-i>" . ale-insert-ctrl-i)
 ("C-o" . ale-insert-ctrl-o))
#+end_src

*** NORMAL
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Keybindings-NORMAL-00dd6416
:END:

#+begin_src emacs-lisp
(meow-normal-define-key
 '("0" . meow-digit-argument)
 '("1" . meow-digit-argument)
 '("2" . meow-digit-argument)
 '("3" . meow-digit-argument)
 '("4" . meow-digit-argument)
 '("5" . meow-digit-argument)
 '("6" . meow-digit-argument)
 '("7" . meow-digit-argument)
 '("8" . meow-digit-argument)
 '("9" . meow-digit-argument)
 '("/" . consult-line)
 '("%" . ale-match-paren)
 '("`" . negative-argument)
 '(";" . meow-reverse)
 '("," . meow-inner-of-thing)
 '("." . meow-bounds-of-thing)
 '("<" . beginning-of-buffer)
 '(">" . end-of-buffer)
 '("[" . scroll-down)
 '("]" . scroll-up)
 '("-" . meow-pop)
 '("_" . meow-pop-all-selection)
 '("=" . ale-query-replace)
 '("+" . anzu-query-replace-regexp)
 '("'" . meow-end-of-thing)
 '("\\" . meow-pop-search)
 '("^" . meow-last-buffer)
 '("<backspace>" . meow-beginning-of-thing)
 '("a" . ale-insert)
 '("A" . ale-insert-at-first-non-whitespace)
 '("b" . meow-back-word)
 '("B" . meow-back-symbol)
 '("c" . meow-change)
 '("C" . meow-change-save)
 '("d" . meow-delete)
 '("e" . meow-line)
 '("E" . ale-inner-line)
 '("f" . meow-next-word)
 '("F" . meow-next-symbol)
 '("g" . ale-files-update)
 '("h" . embrace-commander)
 '("i" . forward-char)
 '("j" . ale-top-join-line)
 '("J" . meow-join)
 '("k" . meow-kill)
 '("K" . meow-kmacro-matches)
 '("l" . meow-kmacro-lines)
 '("m" . meow-mark-word)
 '("M" . meow-mark-symbol)
 '("n" . ale-next-line)
 '("N" . meow-next-expand)
 '("o" . backward-char)
 '("p" . ale-prev-line)
 '("P" . meow-prev-expand)
 '("q" . meow-quit)
 '("r" . meow-search)
 '("s" . meow-open-below)
 '("S" . meow-open-above)
 '("t" . avy-goto-char-timer)
 '("T" . avy-resume)
 '("u" . undo)
 '("U" . undo-redo)
 '("v" . meow-visit)
 '("w" . meow-block)
 '("W" . meow-block-expand)
 '("x" . ale-save)
 '("y" . meow-replace)
 '("Y" . meow-yank-pop)
 '("z" . meow-grab)
 '("Z" . meow-swap-grab))
#+end_src

*** LEADER
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Keybindings-LEADER-0a9580f7
:END:

#+begin_src emacs-lisp
(meow-leader-define-key
 '("0" . delete-window)
 '("1" . delete-other-windows)
 '("2" . ale-split-window-below)
 '("3" . ale-split-window-right)
 '("4" . ctl-x-4-prefix)
 '("5" . ctl-x-5-prefix)
 '("6" . register-map)
 '("7" . project-map)
 '("8" . insert-char)
 '("9" . tab-map)
 '("[" . awesome-tab-backward-tab)
 '("]" . awesome-tab-forward-tab)
 '("SPC" . switch-to-buffer)
 '("?" . describe-keymap)
 '("/" . describe-symbol)
 '(";" . ale-comment-or-uncomment-region)
 '("e" . ale-elisp-map)
 '("f" . ale-files-map)
 '("i" . list-buffers)
 '("k" . kill-this-buffer)
 '("n" . dired-jump)
 '("o" . ale-org-map)
 '("p" . ale-project-find-file)
 '("t" . ale-consult-map)
 '("u" . ale-utils-map)
 '("w" . save-buffer)
 '("z" . window-toggle-side-windows))

(meow-motion-overwrite-define-key
'("/" . consult-line)
'("<escape>" . ale-escape))
#+end_src

*** GLOBAL
:PROPERTIES:
:CUSTOM_ID: *CORE_CONFIGURATION*-Keybindings-GLOBAL-93442e92
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(bind-keys
 :map global-map
 ("<escape>" . ale-escape)
 ("C-;" . exchange-point-and-mark)
 ("<C-i>" . better-jumper-jump-forward)
 ("C-o" . better-jumper-jump-backward)
 ("C-x C-d" . ale-ispell-word)
 ("M-o" . ace-select-window)
 ("M-SPC" . ale-monocle) ; replaced `just-one-space'
 ("M-%" . anzu-isearch-query-replace)
 :map minibuffer-local-map
 ("S-<return>" . ale-files-other-window)
 ("C-u" . ale-kill-whole-line)
 ("<C-i>" . forward-char)
 ("C-o" . backward-char)
 :map ale-files-map
 ("." . ale-files-dotfiles)
 ("e" . ale-files-edit-emacs-config)
 ("u" . ale-files-in-user-dirs)
 ("o" . ale-files-browse-all-directories)
 ("r" . ale-files-rename-file-and-buffer)
 ("l" . find-library)
 :map ale-elisp-map
 ("e" . eval-last-sexp)
 ("x" . eval-expression)
 ("f" . eval-defun)
 ("u" . ale-unadvice)
 ("m" . ale-show-messages)
 ("<backspace>" . ale-erase-messages)
 :map ale-utils-map
 ("d" . ale-insert-date)
 ("o" . ale-opacity-set)
 ("=" . count-words))

(ale-kbd-C-i-fix)
#+end_src

* Introspection
:PROPERTIES:
:CUSTOM_ID: Introspection-2eb9ae27
:END:
** Man page (man.el)
:PROPERTIES:
:CUSTOM_ID: Introspection-Man_page_(man.el)-5c13db67
:END:

#+begin_src emacs-lisp
(use-package man
  :straight (:type built-in)
  :config
  (setq Man-notify-method 'newframe))
#+end_src

** Emacs Manual (info.el)
:PROPERTIES:
:CUSTOM_ID: Introspection-Emacs_Manual_(info.el)-6d9c1f6f
:END:

#+begin_src emacs-lisp
(use-package info
  :straight (:type built-in)
  :bind
  (:map Info-mode-map
        ("n" . next-line)
        ("p" . previous-line)
        ("C-n" . Info-next)
        ("C-p" . Info-prev)
        ("M-n" . forward-paragraph)
        ("M-p" . backward-paragraph)))
#+end_src

** Helpful (helpful.el)
:PROPERTIES:
:CUSTOM_ID: Introspection-Helpful_(helpful.el)-9bea94cb
:END:

Helpful.el provides a better help buffer. Here are some tweaks I
made for this package and built-in help buffer:

- disable auto jump to other end when cycle through buttons never
- open new window when invoking =helpful-visit-references=.  auto
- focus newly opened help buffer (same behaviour as helpful.el)

*** Autoload
:PROPERTIES:
:CUSTOM_ID: Introspection-Helpful_(helpful.el)-Autoload-29b34fed
:END:

#+begin_src emacs-lisp :tangle (ale-init-ext-tangle)
;;; ale-helpful.el --- -*- lexical-binding: t -*-

(defvar ale/helpful-initialized nil)

;;;###autoload
(defun ale/helpful-mode-hook ()
  ;; FIXME: A better way?
  (setq ale/helpful-initialized nil)
  (advice-add 'find-file :before
              (lambda (&rest _)
                (when (and (not ale/helpful-initialized) (derived-mode-p 'helpful-mode))
                  (switch-to-buffer "*scratch*")
                  (switch-to-prev-buffer)
                  (setq ale/helpful-initialized t))))
  (visual-line-mode))

(provide 'ale-helpful)
#+end_src

*** Config
:PROPERTIES:
:CUSTOM_ID: Introspection-Helpful_(helpful.el)-Config-88136d61
:END:

#+begin_src emacs-lisp
(use-package helpful
  :hook (helpful-mode . ale/helpful-mode-hook)
  :bind
  (("C-h K" . #'describe-keymap)  ; overrides `Info-goto-emacs-key-command-node'
   ([remap describe-function] . #'helpful-callable)
   ([remap describe-symbol] . #'helpful-symbol)
   ([remap describe-key] . #'helpful-key)
   :map helpful-mode-map
   ("M-n" . (lambda () (interactive) (forward-button 1 nil 1 t)))
   ("M-p" . (lambda () (interactive) (backward-button 1 nil 1 t)))))
#+end_src

* History
:PROPERTIES:
:CUSTOM_ID: History-b0e9427a
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
;; Keep a record of all recently opened files.
(use-package recentf
  :straight (:type built-in)
  :after-call find-file-hook danger
  :config
  (add-to-list 'recentf-exclude (lambda (f) (not (string= (file-truename f) f))))
  (recentf-mode 1))

;; Just remember where the point is in any given file.  This can often
;; be a subtle reminder of what you were doing the last time you
;; visited that file, allowing you to pick up from there.
(use-package saveplace
  :straight (:type built-in)
  :after-call find-file-hook
  :config
  (setq save-place-file (locate-user-emacs-file "saveplace"))
  (setq save-place-forget-unreadable-files t)
  (save-place-mode 1))

;; This mode ensures that the buffer is updated whenever the file
;; changes.  A change can happen externally or by some other tool
;; inside of Emacs (e.g. kill a Magit diff).
(use-package autorevert
  :straight (:type built-in)
  :after-call self-insert-command
  :config
  (setq auto-revert-verbose t)
  (global-auto-revert-mode))
#+end_src

* UI extras
:PROPERTIES:
:CUSTOM_ID: UI_extras-7d2965b2
:END:

** Smooth scrolling (good-scroll.el)
:PROPERTIES:
:CUSTOM_ID: UI_extras-Smooth_scrolling_(good-scroll.el)-7cf7742a
:END:

pixelwise (linear or bezier) scrolling in emacs.

#+begin_src emacs-lisp
(use-package good-scroll
  :after-call scroll-up scroll-down
  :config
  (good-scroll-mode 1)
  (advice-add 'scroll-up :override 'good-scroll-up-full-screen)
  (advice-add 'scroll-down :override 'good-scroll-down-full-screen))
#+end_src

** Window position (transpose-frame.el)
:PROPERTIES:
:CUSTOM_ID: UI_extras-Window_position_(transpose-frame.el)-52932c1a
:END:

The =transpose-frame= library defines a set of commands for shifting the
layout of Emacs windows.  Rather than me describing how these work, I
strongly encourage you to read the "Commentary" section in the source
code.  Do it with =M-x find-library transpose-frame=.

#+begin_src emacs-lisp
(use-package transpose-frame)
#+end_src

** Fill column (visual-fill-column.el)
:PROPERTIES:
:CUSTOM_ID: UI_extras-Fill_column_(visual-fill-column.el)-0231844f
:END:

#+begin_src emacs-lisp
(use-package visual-fill-column)
#+end_src

** Key bindings hint (which-key.el)
:PROPERTIES:
:CUSTOM_ID: UI_extras-Key_bindings_hint_(which-key.el)-91c2c249
:END:

#+begin_src emacs-lisp
(use-package which-key
  :init
  (which-key-mode 1 ))
#+end_src

** Buffer list (ibuffer.el)
:PROPERTIES:
:CUSTOM_ID: UI_extras-Buffer_list_(ibuffer.el)-42746374
:END:

=ibuffer.el= ships with Emacs and it provides a drop-in replacement for
=list-buffers=.  Compared to its counterpart, it allows for granular
control over the buffer list and is more powerful overall.

#+begin_src emacs-lisp
(use-package ibuffer
  :init
  (advice-add 'list-buffers :override 'ibuffer)
  :bind
  (:map ibuffer-mode-map
        ("M-o" . nil)
        ("* f" . ibuffer-mark-by-file-name-regexp)
        ("* g" . ibuffer-mark-by-content-regexp)
        ("* n" . ibuffer-mark-by-name-regexp)
        ("s n" . ibuffer-do-sort-by-alphabetic)
        ("/ g" . ibuffer-filter-by-content))
  :config
  (setq ibuffer-expert t)
  (setq ibuffer-display-summary nil)
  (setq ibuffer-use-other-window nil)
  (setq ibuffer-show-empty-filter-groups nil)
  (setq ibuffer-movement-cycle nil)
  (setq ibuffer-default-sorting-mode 'filename/process)
  (setq ibuffer-use-header-line t)
  (setq ibuffer-default-shrink-to-minimum-size nil)
  (setq ibuffer-never-show-predicates '("^ \\*.*"))
  (setq ibuffer-formats
        '((mark modified read-only locked " "
                (name 30 30 :left :elide)
                " "
                (size 9 -1 :right)
                " "
                (mode 16 16 :left :elide)
                " " filename-and-process)
          (mark " " (name 16 -1) " " filename)))
  (setq ibuffer-saved-filter-groups nil)
  (setq ibuffer-old-time 48)
  (add-hook 'ibuffer-mode-hook (lambda () (interactive) (hl-line-mode) (ibuffer-update 0))))
#+end_src

* File management
:PROPERTIES:
:CUSTOM_ID: File_management-be510e01
:END:
** Find files (files.el)
:PROPERTIES:
:CUSTOM_ID: File_management-Find_files_(files.el)-e6cb7095
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package files
  :straight (:type built-in)
  :bind
  (:map ale-files-map
        ("r" . ale-dired-jump))
  :config
  (setq confirm-kill-processes nil)
  (setq ale-files-dir-alist
        '(((title . "  Shows")        (path . "/mnt/HDD/Share"))
          ((title . "  Coding")       (path . "/mnt/HDD/Dev"))
          ((title . "  Books")        (path . "/mnt/HDD/Book"))
          ((title . "輸  Videos")       (path . "/mnt/HDD/Video"))
          ((title . "  Movies")       (path . "/mnt/Cloud/共享/Movies"))
          ((title . "  Notes")        (path . "~/Documents/notes"))
          ((title . "  Photos")       (path . "~/Pictures"))
          ((title . "  Downloads")    (path . "~/Downloads")))))
#+end_src

** Dired (dired.el)
:PROPERTIES:
:CUSTOM_ID: File_management-Dired_(dired.el)-aaf2ff97
:END:

=Dired= is a built-in tool that performs file management operations
inside of an Emacs buffer.  It is simply superb!

#+begin_src emacs-lisp (ale-minimal-config)
(use-package dired
  :straight (:type built-in)
  :custom
  (ale-dired-routes '(("o" "Home"        "~")
                      ("u" "Emacs cache" "~/.cache/emacs")
                      ("p" "Code"        "~/Code")
                      ("n" "Downloads"   "~/Downloads")
                      ("w" "Wallpaper"   "~/Pictures/wallpaper")
                      ("m" "Drives"      "/mnt")
                      ("t" "Trash"       "~/.local/share/Trash")))
  :bind
  (:map dired-mode-map
        ("/" . dired-goto-file)
        ("a" . dired-create-empty-file)
        ("r" . ale-dired-jump)
        ("I" . dired-insert-subdir)
        ("?" . dired-create-directory)
        ("^" . dired-find-file-other-window)
        ("i" . ale-dired-file-rename-eol)
        ("d" . dired-kill-subdir)
        ("<" . beginning-of-buffer)
        (">" . end-of-buffer)
        ("[" . dired-prev-dirline)
        ("]" . dired-next-dirline)
        ("o" . dired-up-directory)
        ("x" . dired-do-delete)
        ("." . dired-omit-mode)
        ("% SPC" . ale-dired-rename-space-to-underscore))
  :config
  (setq large-file-warning-threshold 50000000)
  (setq dired-recursive-copies 'always)
  (setq dired-recursive-deletes 'always)
  (setq delete-by-moving-to-trash t)
  (setq dired-dwim-target t)
  (setq dired-listing-switches "-AGhlv --group-directories-first --time-style=long-iso"))
#+end_src

** Writable dired (wdired.el)
:PROPERTIES:
:CUSTOM_ID: File_management-Writable_dired_(wdired.el)-5880191e
:END:

#+begin_src emacs-lisp
(use-package wdired
  :config
  (setq wdired-allow-to-change-permissions t)
  (setq wdired-create-parent-directories t))
#+end_src

** Project management (project.el)
:PROPERTIES:
:CUSTOM_ID: File_management-Project_management_(project.el)-af77825b
:END:

#+begin_src emacs-lisp
(use-package project
  :straight (:type built-in)
  :config
  (setq project-switch-commands
        '((project-find-file "File" ?\r)
          (ale-project-find-subdir "Subdir" ?s)
          (project-find-regexp "Grep" ?g)
          (project-dired "Dired" ?d)
          (ale-project-retrieve-tag "Tag switch" ?t)
          (ale-project-magit-status "Magit" ?m)
          (ale-project-commit-log "Log VC" ?l)))
  (setq ale-project-commit-log-limit 25)
  :bind
  (:map project-prefix-map
        ("l" . ale-project-commit-log)
        ("m" . ale-project-magit-status)
        ("s" . ale-project-find-subdir)
        ("t" . ale-project-retrieve-tag)))
#+end_src

** A better dired interface (danger.el)
:PROPERTIES:
:CUSTOM_ID: File_management-A_better_dired_interface_(danger.el)-d6097293
:END:

This package is inspired the popular file manager =ranger=, I created it
on the basis of =ranger.el=. Compare to =ranger.el=, this package only
keeps features I wanted, and some sensible functionalities were added
as well. See details at: https://github.com/alexluigit/danger.el

#+begin_src emacs-lisp
(use-package danger
  :after-call pre-command-hook
  :straight (danger :type git :depth full :host github :repo "alexluigit/danger.el")
  :hook
  (danger-mode . (lambda () (setq cursor-type nil) (setq mode-line-format nil)))
  :config
  (danger-override-dired-mode)
  (danger-minibuf-preview-mode)
  (setq danger-trash-dir-alist '(("/mnt/HDD/" . ".Trash/files")
                                 ("/mnt/Cloud/" . ".Trash/files"))))
#+end_src

** Dired mode highlighting (diredfl.el)
:PROPERTIES:
:CUSTOM_ID: File_management-Dired_mode_highlighting_(diredfl.el)-638b0aa2
:END:

Additional syntax highlighting in dired buffer.

#+begin_src emacs-lisp
(use-package diredfl
  :hook (dired-mode . diredfl-mode))
#+end_src

** Trash (trashed.el)
:PROPERTIES:
:CUSTOM_ID: File_management-Trash_(trashed.el)-ed792e53
:END:

=trashed= applies the principles of =dired= to the management of the user's
filesystem trash.  Use =C-h m= to see the docs and keybindings for its
major mode.

Basically, its interaction model is as follows:

- =m= to mark for some deferred action, such as =D= to delete, =R= to restore.
- =t= to toggle the status of all items as marked.  Use this without marks
  to =m= (mark) all items, then call a deferred action to operate on them.
- =d= to mark for permanent deletion.
- =r= to mark for restoration.
- =x= to execute these special marks.

#+begin_src emacs-lisp
(use-package trashed
  :config
  (setq trashed-action-confirmer 'y-or-n-p)
  (setq trashed-use-header-line t)
  (setq trashed-sort-key '("Date deleted" . t))
  (setq trashed-date-format "%Y-%m-%d %H:%M:%S"))
#+end_src

* Text editing extras
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-f1492905
:END:
** Long line text (so-long.el)
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Long_line_text_(so-long.el)-22aa03c8
:END:

Consistent performance is the reason to enable =global-so-long-mode=, built
into Emacs versions >= 27, which allows the active major mode to gracefully
adapt to buffers with very long lines. What “very long” means is, of course,
configurable: M-x find-library so-long covers several customisation options,
though I find that the defaults require no further intervention from my part.

#+begin_src emacs-lisp
(use-package so-long
  :after-call find-file-hook
  :straight (:type built-in)
  :config
  (global-so-long-mode))
#+end_src

** Writable grep (wgrep.el)
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Writable_grep_(wgrep.el)-7dd75e82
:END:

With =wgrep= we can directly edit the results of a grep and save the changes to
all affected buffers.  In principle, this is the same as what the built-in occur
offers.  We can use it to operate on a list of matches by leveraging the full
power of Emacs' editing capabilities (e.g. keyboard macros, query and replace a
regexp .etc).

#+begin_src emacs-lisp
(use-package wgrep
  :config
  (setq wgrep-auto-save-buffer t)
  (setq wgrep-change-readonly-file t)
  :bind
  (:map wgrep-mode-map
        ("M-n" . next-error-no-select)
        ("M-p" . previous-error-no-select)))
#+end_src

** Auto completion (company.el)
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Auto_completion_(company.el)-e267ab38
:END:

  =tng= means tab and go, in this mode tab key will complete and
  move to the next candidate meanwhile keep company window open.

#+begin_src emacs-lisp
(use-package company
  :after-call self-insert-command
  :config
  (global-company-mode)
  (company-tng-mode)
  (setq company-idle-delay 0.0))
#+end_src

** Pair insertion
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Pair_insertion-6dedc71d
:END:

Emacs labels as `electric' any behaviour that involves contextual auto-insertion
of characters.

- Indent automatically.

- If =electric-pair-mode= is enabled (which I might do manually),
  insert quotes and brackets in pairs.  Only do so if there is no
  alphabetic character after the cursor.

- To get those numbers, evaluate =(string-to-char CHAR)= where CHAR
  is the one you are interested in.  For example, get the literal
  tab's character with `(string-to-char "\t")'.

- While inputting a pair, inserting the closing character will just
  skip over the existing one, rather than add a new one.

- Do not skip over whitespace when operating on pairs.  Combined
  with the above point, this means that a new character will be
  inserted, rather than be skipped over.  I find this better,
  because it prevents the point from jumping forward, plus it
  allows for more natural editing.

- The rest concern the conditions for transforming quotes into
  their curly equivalents.  I keep this disabled, because curly
  quotes are distinct characters.  It is difficult to search for
  them.  Just note that on GNU/Linux you can type them directly by
  hitting the "compose" key and then an angled bracket (=<= or =>=)
  followed by a quote mark.

#+begin_src emacs-lisp
(use-package electric
  :config
  (advice-add 'electric-pair-post-self-insert-function :around
              (lambda (fn &rest args) (let ((mark-active nil)) (apply fn args))))
  (setq electric-pair-inhibit-predicate 'electric-pair-conservative-inhibit)
  (setq electric-pair-preserve-balance t)
  (setq electric-pair-pairs
        '((8216 . 8217)
          (8220 . 8221)
          (171 . 187)))
  (setq electric-pair-skip-self 'electric-pair-default-skip-self)
  (setq electric-pair-skip-whitespace nil)
  (setq electric-pair-skip-whitespace-chars '(9 10 32))
  (setq electric-quote-context-sensitive t)
  (setq electric-quote-paragraph t)
  (setq electric-quote-string nil)
  (setq electric-quote-replace-double t)
  (electric-indent-mode 1)
  (electric-pair-mode 1)
  (electric-quote-mode -1)
  :hook
  (org-mode . ale-electric-inhibit-<)
  (minibuffer-setup . (lambda () (unless (eq this-command 'eval-expression) (electric-pair-mode 0))))
  (minibuffer-exit . (lambda () (electric-pair-mode 1))))
#+end_src

** Parentheses (paren.el / rainbow-delimiters.el)
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Parentheses_(paren.el__rainbow-delimiters.el)-fd6e149d
:END:

Configure the mode that highlights matching delimiters or parentheses.
I consider this of utmost importance when working with languages such as
elisp.

Summary of what these do:

- Activate the mode upon startup.
- Show the matching delimiter/parenthesis if on screen, else show
  nothing.  It is possible to highlight the expression enclosed by the
  delimiters, by using either =mixed= or =expression=.  The latter always
  highlights the entire balanced expression, while the former will only
  do so if the matching delimiter is off screen.
- =show-paren-when-point-in-periphery= lets you highlight parentheses even
  if the point is in their vicinity.  This means the beginning or end of
  the line, with space in between.  I used that for a long while and it
  server me well.  Now that I have a better understanding of Elisp, I
  disable it.
- Do not highlight a match when the point is on the inside of the
  parenthesis.
- Use rainbow color for delimiters

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package paren
  :straight (:type built-in)
  :after-call meow-block meow-line self-insert-command
  :config
  (setq show-paren-style 'parenthesis)
  (setq show-paren-when-point-in-periphery nil)
  (setq show-paren-when-point-inside-paren nil)
  (show-paren-mode))

(use-package rainbow-delimiters
  :hook
  (prog-mode . rainbow-delimiters-mode))
#+end_src

** Prettify symbols (prog-mode.el)
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Prettify_symbols_(prog-mode.el)-1e9c6d6a
:END:

#+begin_src emacs-lisp
(use-package prog-mode
  :straight nil
  :hook (prog-mode . prettify-symbols-mode)
  :config
  (setq-default prettify-symbols-alist
                '(("lambda" . ?λ)
                  ("<-" . ?←)
                  ("->" . ?→)
                  ("->>" . ?↠)
                  ("=>" . ?⇒)
                  ("/=" . ?≠)
                  ("!=" . ?≠)
                  ("==" . ?≡)
                  ("<=" . ?≤)
                  (">=" . ?≥)
                  ("=<<" . (?= (Br . Bl) ?≪))
                  (">>=" . (?≫ (Br . Bl) ?=))
                  ("<=<" . ?↢)
                  (">=>" . ?↣)))
  (setq prettify-symbols-unprettify-at-point 'right-edge))
#+end_src

** Ripgrep (rg.el)
:PROPERTIES:
:CUSTOM_ID: Text_editing_extras-Ripgrep_(rg.el)-80b9a72d
:END:

#+begin_src emacs-lisp
(defun ale/rg-config ()
  (rg-define-toggle "--context 3" (kbd "C"))
  (rg-define-toggle "-A 5" (kbd "A")))

(use-package rg
  :config
  ;;; XXX nasty hack for lazy loading
  (ale/rg-config)
  :bind
  (:map ale-utils-map
        ("r" . rg)))
#+end_src

* Languages
:PROPERTIES:
:CUSTOM_ID: Languages-fc24530b
:END:
** .rs
:PROPERTIES:
:CUSTOM_ID: Languages-.rs-30487163
:END:

#+begin_src emacs-lisp
(use-package rust-mode
  :hook
  (rust-mode . (lambda () (setq indent-tabs-mode nil))))
#+end_src

** .lua
:PROPERTIES:
:CUSTOM_ID: Languages-.lua-5a72c6cb
:END:

#+begin_src emacs-lisp
(use-package lua-mode
  :config
  (setq lua-indent-level 2))
#+end_src

** .yaml
:PROPERTIES:
:CUSTOM_ID: Languages-.yaml-f1b33707
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package yaml-mode)
#+end_src

** .vue
:PROPERTIES:
:CUSTOM_ID: Languages-.vue-cf7c3bbb
:END:

#+begin_src emacs-lisp
(use-package web-mode
  :config
  (define-derived-mode ale/vue-mode web-mode "ale/vue"
    "A major mode derived from web-mode, for editing .vue files with LSP support.")
  :hook
  (web-mode . (lambda ()
                (setq web-mode-markup-indent-offset 2)
                (setq web-mode-code-indent-offset 2)
                (setq web-mode-script-padding 0)))
  :mode ("\\.vue\\'" . ale/vue-mode))
#+end_src

** .js
:PROPERTIES:
:CUSTOM_ID: Languages-.js-a8b50c48
:END:

#+begin_src emacs-lisp
(use-package js
  :straight (:type built-in)
  :config
  (setq js-indent-level 2))
#+end_src

** .(sh|zsh)
:PROPERTIES:
:CUSTOM_ID: Languages-.(sh|zsh)-accbc402
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package sh-script
  :straight (:type built-in)
  :config
  (setq sh-basic-offset 2))
#+end_src

* DevTools
:PROPERTIES:
:CUSTOM_ID: DevTools-b43b796a
:END:
** LSP (lsp.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-LSP_(lsp.el)-8174ab3f
:END:
*** Autoload
:PROPERTIES:
:CUSTOM_ID: DevTools-LSP_(lsp.el)-Autoload-50e36585
:END:

#+begin_src emacs-lisp :tangle (ale-init-ext-tangle)
;;; ale-lsp.el --- -*- lexical-binding: t -*-

(defun ale/lsp--inhibit ()
  "Disable `lsp-deferred' in minibuffer."
  (advice-add 'lsp-deferred :override #'ignore))

(defun ale/lsp--recover ()
  "Recover `lsp-deferred' after quit minibuffer."
  (advice-remove 'lsp-deferred #'ignore))

;;;###autoload
(define-minor-mode ale/lsp-mode
  "Inhibit lsp in minibuffer."
  :init-value nil
  :global t
  (if ale/lsp-mode
      (progn
      (add-hook 'minibuffer-setup-hook 'ale/lsp--inhibit)
      (add-hook 'minibuffer-exit-hook 'ale/lsp--recover))
    (progn
      (remove-hook 'minibuffer-setup-hook 'ale/lsp--inhibit)
      (remove-hook 'minibuffer-exit-hook 'ale/lsp--recover))))

(provide 'ale-lsp)
#+end_src

*** Config
:PROPERTIES:
:CUSTOM_ID: DevTools-LSP_(lsp.el)-Config-090e755b
:END:

#+begin_src emacs-lisp
(use-package lsp-mode
  :after-call pre-command-hook
  :hook ((sh-mode
          lua-mode
          ale/vue-mode
          typescript-mode
          rust-mode)
         . lsp-deferred)
  :config
  (ale/lsp-mode)
  (setq lsp-eldoc-hook nil)
  (setq lsp-server-install-dir (expand-file-name (concat user-emacs-directory "lsp")))
  (lsp-register-custom-settings '(("vetur.ignoreProjectWarning" t t)))
  (with-eval-after-load 'warnings
    (add-to-list 'warning-suppress-types '(lsp-mode)))
  (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols)))
#+end_src

*** Extensions
:PROPERTIES:
:CUSTOM_ID: DevTools-LSP_(lsp.el)-Extensions-1f239010
:END:

#+begin_src emacs-lisp
(use-package lsp-tailwindcss
  :after (lsp-mode web-mode)
  :init
  (setq lsp-tailwindcss-add-on-mode t))

(use-package lsp-ui
  :after-call lsp-deferred
  :config
  (setq lsp-ui-sideline-show-code-actions nil)
  (setq lsp-ui-doc-position 'bottom)
  :hook
  (lsp-mode . lsp-ui-mode))
#+end_src

** Colorizer (rainbow-mode.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-Colorizer_(rainbow-mode.el)-682426c1
:END:

#+begin_src emacs-lisp
(use-package rainbow-mode
  :hook
  (prog-mode . rainbow-mode))
#+end_src

** Formatter (format-all.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-Formatter_(format-all.el)-8dd1b7d6
:END:

#+begin_src emacs-lisp
(use-package format-all
  :bind ("C-c C-M-f" . format-all-buffer))
#+end_src

** Syntax checker (flymake.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-Syntax_checker_(flymake.el)-4a7acf9b
:END:

#+begin_src emacs-lisp
(use-package flymake
  :straight (:type built-in)
  :config
  (setq elisp-flymake-byte-compile-load-path
        (append elisp-flymake-byte-compile-load-path load-path))
  (setq flymake-fringe-indicator-position 'left-fringe)
  (setq flymake-suppress-zero-counters t)
  (setq flymake-start-on-flymake-mode t)
  (setq flymake-no-changes-timeout nil)
  (setq flymake-start-on-save-buffer t)
  (setq flymake-proc-compilation-prevents-syntax-check t)
  (setq flymake-wrap-around nil)
  :bind
  (:map flymake-mode-map
  ("C-c ! s" . flymake-start)
  ("C-c ! d" . flymake-show-diagnostics-buffer)
  ("C-c ! n" . flymake-goto-next-error)
  ("C-c ! p" . flymake-goto-prev-error)))
#+end_src

** Snippet (yasnippet.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-Snippet_(yasnippet.el)-640404f6
:END:

#+begin_src emacs-lisp
(use-package yasnippet
  :after-call self-insert-command
  :config
  (yas-global-mode))
#+end_src

** REST client (restclient.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-REST_client_(restclient.el)-40c2f65f
:END:

#+begin_src emacs-lisp
(use-package restclient)
#+end_src

** Scratch buffers (scratch.el)
:PROPERTIES:
:CUSTOM_ID: DevTools-Scratch_buffers_(scratch.el)-13244292
:END:

This package will produce a buffer that matches the major mode of the
one you are currently in.  Use it with =M-x scratch=.  Doing that with a
prefix argument (=C-u=) will prompt for a major mode instead.  Simple yet
super effective!

The =ale/scratch-buffer-setup= simply adds some text in the buffer and
renames it appropriately for the sake of easier discovery.  I got the
idea of copying the region from [[https://gist.github.com/eev2/52edbfdb645e26aefec19226c0ca7ad0][a snippet shared by eev2 on GitHub]].

*** Autoload
:PROPERTIES:
:CUSTOM_ID: DevTools-Scratch_buffers_(scratch.el)-Autoload-0d1b6a79
:END:

#+begin_src emacs-lisp :tangle (ale-init-ext-tangle)
;;; ale-scratch.el --- -*- lexical-binding: t -*-

;;;###autoload
(defun ale/scratch-buffer-setup ()
  "Add contents to `scratch' buffer and name it accordingly.
If region is active, add its contents to the new buffer."
  (let* ((mode major-mode)
         (string (format "Scratch buffer for: %s\n\n" mode))
         (region (with-current-buffer (current-buffer)
                   (if (region-active-p)
                       (buffer-substring-no-properties
                        (region-beginning)
                        (region-end)))
                   ""))
         (text (concat string region)))
    (when scratch-buffer
      (save-excursion
        (insert text)
        (goto-char (point-min))
        (comment-region (point-at-bol) (point-at-eol)))
      (forward-line 2))
    (rename-buffer (format "*Scratch for %s*" mode) t)))
#+end_src

*** Config
:PROPERTIES:
:CUSTOM_ID: DevTools-Scratch_buffers_(scratch.el)-Config-c1c518ba
:END:

#+begin_src emacs-lisp
(use-package scratch
  :hook (scratch-create-buffer . ale/scratch-buffer-setup)
  :bind (("C-c s" . scratch)
         :map ale-files-map
         ("s" . scratch)))
#+end_src

* Terminal
:PROPERTIES:
:CUSTOM_ID: Terminal-8abe3efe
:END:
** Vterm (vterm.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-Vterm_(vterm.el)-adf87065
:END:
*** Autoload
:PROPERTIES:
:CUSTOM_ID: Terminal-Vterm_(vterm.el)-Autoload-0d3e43e5
:END:

#+begin_src emacs-lisp :tangle (ale-init-ext-tangle)
;;; ale-vterm.el --- -*- lexical-binding: t -*-

(defcustom ale/vterm-position
  '((danger-mode . ((window-height . 0.4) (side . bottom)))
    (default . ((window-width . 0.4) (side . right))))
  "doc")

(defvar ale/vterm-buffers nil
  "The list of non-dedicated vterm buffers.")

(defvar ale/vterm-index 0
  "The index of current vterm buffer.")

(add-hook 'kill-buffer-hook
          (lambda ()
            (let* ((buf (current-buffer))
                   (name (buffer-name buf)))
              (when (string-prefix-p "*vterm" name)
                (delq! buf ale/vterm-buffers)))))

;;;###autoload
(defun ale/vterm--disable-side-window (fn &rest args)
  "Prevent vterm size adjust break selection."
  (unless (and (region-active-p)
               (derived-mode-p 'vterm-mode))
    (apply fn args)))

;;;###autoload
(advice-add 'display-buffer-in-side-window :around 'ale/vterm--disable-side-window)

;;;###autoload
(defun vterm-send-C-delete ()
  (interactive)
  (vterm-send-key "<delete>" nil nil 0))

;;;###autoload
(defun vterm-send-M-return ()
  (interactive)
  (vterm-send-escape)
  (vterm-send-return))

;;;###autoload
(defun vterm-send-M-/ ()
  (interactive)
  (vterm-send-key "/" nil 0 nil))

;;;###autoload
(defun vterm-send-F5 ()
  (interactive)
  (vterm-send-key "<f5>" nil nil nil))

;;;###autoload
(defun vterm-send-M-apostrophe ()
  (interactive)
  (vterm-send-key "'" nil 0 nil))

;;;###autoload
(defun vterm-send-M-quote ()
  (interactive)
  (vterm-send-key "\"" nil 0 nil))

(defun ale/vterm--get-win-params ()
  "Parse `ale/vterm-position' to get vterm display parameters."
  (let (pos)
    (cl-dolist (setting ale/vterm-position)
        (when (derived-mode-p (car setting))
          (setq pos (cdr setting)) (cl-return))
        (when (eq (car setting) 'default)
          (setq pos (cdr setting))))
    `(("^\\*vterm.*"
       (display-buffer-in-side-window)
       (window-parameters . ((mode-line-format . none)))
       ,@pos))))

;;;###autoload
(defun ale/vterm-toggle (&optional force)
  "Toggle vterm.
If called with prefix argument, create a new vterm buffer if
current one have different `default-directory'."
  (interactive "P")
  (if (eq major-mode 'vterm-mode)
      (delete-window)
    (let* ((display-buffer-alist (ale/vterm--get-win-params))
           (buf (nth ale/vterm-index ale/vterm-buffers))
           (dir (expand-file-name default-directory))
           (index (if buf (ale/vterm--get-index buf) 0)))
      (add-to-list 'ale/vterm-buffers (vterm index))
      (when force
        (unless (string= dir (expand-file-name default-directory))
          (let ((default-directory dir))
            (ale/vterm-new))))
      (ale/vterm--insert))))

(defun ale/vterm--get-index (buf)
  (let* ((name (buffer-name buf)))
    (string-match "\\*vterm\\*\<\\([0-9]+\\)\>" name)
    (string-to-number (cl-subseq name (match-beginning 1) (match-end 1)))))

(defun ale/vterm--insert ()
  (when (featurep 'evil) (evil-insert-state))
  (when (featurep 'meow) (meow-insert)))

;;;###autoload
(defun ale/vterm-new ()
  "Create new vterm buffer."
  (interactive)
  (let ((new-index (1+ (ale/vterm--get-index (car ale/vterm-buffers))))
        (display-buffer-alist (ale/vterm--get-win-params)))
    (add-to-list 'ale/vterm-buffers (vterm new-index))
    (ale/vterm--insert)))

;;;###autoload
(defun ale/vterm-next (&optional arg)
  "Select next vterm buffer.
Create new one if no vterm buffer exists."
  (interactive "P")
  (let* ((curr-index (cl-position (current-buffer) ale/vterm-buffers))
         (new-index (+ curr-index (or arg -1)))
         (buf (nth new-index ale/vterm-buffers)))
    (when buf
      (switch-to-buffer buf)
      (setq ale/vterm-index new-index))))

;;;###autoload
(defun ale/vterm-prev (&optional arg)
  "Select previous vterm buffer."
  (interactive "p")
  (ale/vterm-next arg))

(provide 'ale-vterm)
#+end_src

*** Config
:PROPERTIES:
:CUSTOM_ID: Terminal-Vterm_(vterm.el)-Config-4023f865
:END:

#+begin_src emacs-lisp
(use-package vterm
  :config
  (setq vterm-max-scrollback 5000)
  (set-face-attribute 'vterm-color-white nil :foreground "#cccccc")
  (set-face-attribute 'vterm-color-black nil :foreground "#111111")
  :bind
  (("M-v" . ale/vterm-toggle)
   :map vterm-mode-map
   ("M-v" . ale/vterm-toggle)
   ("<f12>" . ale/vterm-new)
   ("M-'" . vterm-send-M-apostrophe)
   ("M-\"" . vterm-send-M-quote)
   ("M-/" . vterm-send-M-/)
   ("M-RET" . vterm-send-M-return)
   ("s-n" . vterm-next-prompt)
   ("s-p" . vterm-previous-prompt)
   ("M-." . ale/vterm-next)
   ("M-," . ale/vterm-prev)
   ("S-<escape>" . (lambda () (interactive) (meow-normal-mode) (meow--update-cursor)))
   ("C-<delete>" . vterm-send-C-delete)
   ("C-<return>" . vterm-send-F5)))
#+end_src

** COMMENT Eshell (eshell.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-Eshell_(eshell.el)-4bd8a590
:END:
*** Autoload
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Autoload-b2c03498
:END:

#+begin_src emacs-lisp :tangle (ale-init-ext-tangle)
;;; ale-eshell.el --- -*- lexical-binding: t -*-

(require 'em-hist)
(eval-when-compile (require 'subr-x))
(require 'cl-seq)

(defcustom ale/eshell-position
  '((danger-mode . ((window-height . 0.4) (side . bottom)))
    (default . ((window-width . 0.4) (side . right))))
  "doc")

(defvar ale/eshell-buffers nil
  "The list of non-dedicated eshell buffers.")

(defvar ale/eshell-index 0
  "The index of current eshell buffer.")

(defun ale/get-current-package-version ()
  (interactive)
  (let ((package-json-file (concat (eshell/pwd) "/package.json")))
    (when (file-exists-p package-json-file)
      (let* ((package-json-contents (ale-f-read package-json-file))
             (package-json (ignore-errors (json-parse-string package-json-contents))))
        (when package-json
          (ignore-errors (gethash "version" package-json)))))))

(defun ale/map-line-to-status-char (line)
  (cond ((string-match "^?\\? " line) "?")))

(defun ale/get-git-status-prompt ()
  (let ((status-lines (cdr (process-lines "git" "status" "--porcelain" "-b"))))
    (seq-uniq (seq-filter 'identity (mapcar 'ale/map-line-to-status-char status-lines)))))

(defun ale/get-prompt-path ()
  (let* ((current-path (eshell/pwd))
         (git-output (shell-command-to-string "git rev-parse --show-toplevel"))
         (has-path (not (string-match "^fatal" git-output))))
    (if (not has-path)
        (abbreviate-file-name current-path)
      (string-remove-prefix (file-name-directory git-output) current-path))))

;; This prompt function mostly replicates my custom zsh prompt setup
(defun ale/eshell-prompt ()
  (let* ((br-cmd "git symbolic-ref HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null")
         (br-raw (shell-command-to-string br-cmd))
         (current-branch (replace-regexp-in-string "\\(refs/heads/\\)\\|\\(\n\\)$" "" br-raw))
         (shell-index (number-to-string (ale/eshell-get--index (current-buffer))))
         (package-version (ale/get-current-package-version)))
    (concat
     (if (= (user-uid) 0)
         (propertize (concat "S-" shell-index) 'face `(:foreground "red2"))
       (propertize (concat "S-" shell-index) 'face `(:foreground "#62aeed")))
     (propertize " • " 'face `(:foreground "white"))
     (propertize "  " 'face `(:foreground "#82cfd3"))
     (propertize (ale/get-prompt-path) 'face `(:foreground "#82cfd3"))
     (when (not (string= current-branch ""))
       (concat
        (propertize " • " 'face `(:foreground "white"))
        (propertize (concat " " current-branch) 'face `(:foreground "#ab98b5"))))
     (when package-version
       (concat
        (propertize " @ " 'face `(:foreground "white"))
        (propertize package-version 'face `(:foreground "#e8a206"))))
     (propertize " • " 'face `(:foreground "white"))
     (propertize (format-time-string "%I:%M:%S %p") 'face `(:foreground "#5a5b7f"))
     (if (= eshell-last-command-status 0)
         (propertize "\nλ" 'face `(:foreground "#ADCF44"))
       (propertize "\nλ" 'face `(:foreground "#EC6261")))
     (propertize " " 'face `(:foreground "white")))))

;;;###autoload
(defun ale/eshell-init ()
  (push 'eshell-tramp eshell-modules-list)
  ;; Save command history when commands are entered
  (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)
  ;; Truncate buffer for performance
  (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)
  (define-key eshell-hist-mode-map (kbd "M-r") 'consult-history)
  ;; Initialize the shell history
  (eshell-hist-initialize)
  (setenv "PAGER" "cat")
  (setq eshell-prompt-function      'ale/eshell-prompt)
  (setq eshell-prompt-regexp        "^λ ")
  (setq eshell-history-size         10000)
  (setq eshell-buffer-maximum-lines 10000)
  (setq eshell-hist-ignoredups t)
  (setq eshell-highlight-prompt t)
  (setq eshell-scroll-to-bottom-on-input t)
  (setq eshell-prefer-lisp-functions nil))

(add-hook 'eshell-exit-hook
          (lambda () (setq ale/eshell-buffers (delq (current-buffer) ale/eshell-buffers))))

;;;###autoload
(defun ale/eshell-updir ()
  "Up a directory in eshell."
  (interactive)
  (eshell/cd "..")
  (eshell-emit-prompt))

(defun ale/eshell--get-win-params ()
  "Parse `ale/eshell-position' to get eshell display parameters."
  (let (pos)
    (cl-dolist (setting ale/eshell-position)
        (when (derived-mode-p (car setting))
          (setq pos (cdr setting)) (cl-return))
        (when (eq (car setting) 'default)
          (setq pos (cdr setting))))
    `(("^\\*[e]shell.*"
       (display-buffer-in-side-window)
       (window-parameters . ((mode-line-format . none)))
       ,@pos))))

;;;###autoload
(defun ale/eshell-toggle (&optional force-new)
  "Toggle eshell.
If called with prefix argument, create a new eshell buffer if
current one have different `default-directory'."
  (interactive "P")
  (if (eq major-mode 'eshell-mode)
      (delete-window)
    (let* ((display-buffer-alist (ale/eshell--get-win-params))
           (buf (nth ale/eshell-index ale/eshell-buffers))
           (dir (expand-file-name default-directory))
           (index (if buf (ale/eshell-get--index buf) 0)))
      (add-to-list 'ale/eshell-buffers (eshell index))
      (when force-new
        (unless (string= dir (expand-file-name default-directory))
          (let ((default-directory dir))
            (ale/eshell-new))))
      (when (featurep 'evil) (evil-insert-state))
      (when (featurep 'meow) (meow-insert)))))

(defun ale/eshell-get--index (buf)
  (let* ((name (buffer-name buf)))
    (string-match "\\*eshell\\*\<\\([0-9]+\\)\>" name)
    (string-to-number (cl-subseq name (match-beginning 1) (match-end 1)))))

;;;###autoload
(defun ale/eshell-new ()
  "Create new eshell buffer."
  (interactive)
  (let ((new-index (1+ (ale/eshell-get--index (car ale/eshell-buffers))))
        (display-buffer-alist (ale/eshell--get-win-params)))
    (add-to-list 'ale/eshell-buffers (eshell new-index))
    (when (featurep 'evil) (evil-insert-state))
    (when (featurep 'meow) (meow-insert))))

;;;###autoload
(defun ale/eshell-next (&optional arg)
  "Select next eshell buffer.
Create new one if no eshell buffer exists."
  (interactive "P")
  (let* ((curr-index (cl-position (current-buffer) ale/eshell-buffers))
         (new-index (+ curr-index (or arg -1)))
         (buf (nth new-index ale/eshell-buffers)))
    (when buf
      (switch-to-buffer buf)
      (setq ale/eshell-index new-index))))

;;;###autoload
(defun ale/eshell-prev (&optional arg)
  "Select previous eshell buffer."
  (interactive "p")
  (ale/eshell-next arg))

;;;###autoload
(defun ale/eshell-clear-buffer ()
  "Clear eshell buffer."
  (interactive)
  (let ((inhibit-read-only t))
    (erase-buffer)
    (eshell-send-input nil nil t)))

(provide 'ale-eshell)
#+end_src

*** Multi-eshell
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Multi-eshell-3754f282
:END:

A poor man's multi-eshell.

#+begin_src emacs-lisp
(use-package esh-mode
  :straight (:type built-in)
  :config
  (setq eshell-banner-message "")
  :hook
  (eshell-first-time-mode . ale/eshell-init)
  :bind
  (("<delete>" . ale/eshell-toggle)
   ("<deletechar>" . ale/eshell-toggle)
   :map eshell-mode-map
   ("M-<delete>" . ale/eshell-new)
   ("C-l" . ale/eshell-clear-buffer)
   ("C-\\" . ale/eshell-updir)
   ("s-n" . eshell-next-prompt)
   ("s-p" . eshell-previous-prompt)
   ("M-." . ale/eshell-next)
   ("M-," . ale/eshell-prev)))
#+end_src

*** Aliases
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Aliases-d72008e1
:END:

This section will be tangled to `eshell-aliases-file'.

#+begin_src conf :tangle (concat user-emacs-directory "eshell/alias")
alias e find-file-other-window $1
alias ls exa -a --color=always --group-directories-first $*
alias la exa -al --color=always --group-directories-first $*
alias ll exa -lu --color=always --group-directories-first --no-user --no-permissions -@ $*
alias lt exa -aT --color=always --git-ignore -I=.git --group-directories-first $*
alias ka killall $1
alias px export HTTP_PROXY=http://127.0.0.1:1088; export HTTPS_PROXY=http://127.0.0.1:1088
alias yd youtube-dl --proxy 127.0.0.1:1088 --write-sub --write-auto-sub -o "~/Downloads/%(title)s-%(id)s.%(ext)s" $1
alias ydl youtube-dl --proxy 127.0.0.1:1088 --yes-playlist --write-sub --write-auto-sub -o "~/Downloads/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" $1
alias y yarn $*
alias ys yarn dev
alias rs rsync $*
alias rsa rsync -avz $*
#+end_src

*** Colors (xterm-color.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Colors_(xterm-color.el)-b5a5a91b
:END:

We want to use xterm-256color when running interactive commands in eshell but
not during other times when we might be launching a shell command to gather its
output.

#+begin_src emacs-lisp
(use-package xterm-color
  :after esh-mode
  :config
  (push 'xterm-color-filter eshell-preoutput-filter-functions)
  (add-hook 'eshell-pre-command-hook (lambda () (setenv "TERM" "xterm-256color")))
  (add-hook 'eshell-post-command-hook (lambda () (setenv "TERM" "dumb")))
  (add-hook 'eshell-before-prompt-hook (lambda () (setq xterm-color-preserve-properties t)))
  (delq 'eshell-handle-ansi-color eshell-output-filter-functions))
#+end_src

*** Fish like Completion (fish-completion.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Fish_like_Completion_(fish-completion.el)-64f8d46e
:END:

This enhances eshell's completions with those that Fish is capable of and also
falls back to any additional completions that are configured for Bash on the
system.  The primary benefit here (for me) is getting completion for commits and
branches in =git= commands.

#+begin_src emacs-lisp
(use-package fish-completion
  :hook (eshell-mode . fish-completion-mode))
#+end_src

*** Z navigation (eshell-z.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Z_navigation_(eshell-z.el)-cdf7e228
:END:

#+begin_src emacs-lisp
(use-package eshell-z
  :hook ((eshell-first-time-mode . (lambda () (require 'eshell-z)))
         (eshell-z-change-dir .  (lambda () (eshell/pushd (eshell/pwd))))))
#+end_src

*** Highlighting (eshell-syntax-highlighting.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-Highlighting_(eshell-syntax-highlighting.el)-9ddab42c
:END:

#+begin_src emacs-lisp
(use-package eshell-syntax-highlighting
  :after esh-mode
  :config
  (eshell-syntax-highlighting-global-mode +1))
#+end_src

*** History completion (esh-autosuggest.el)
:PROPERTIES:
:CUSTOM_ID: Terminal-COMMENT_Eshell_(eshell.el)-History_completion_(esh-autosuggest.el)-e0aa9d43
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package esh-autosuggest
  :hook (eshell-mode . esh-autosuggest-mode)
  :bind
  (:map esh-autosuggest-active-map
        ("M-f" . esh-autosuggest-complete-word)
        ("C-e" . company-complete-selection))
  :config
  (set-face-foreground 'company-preview-common "#4b5668")
  (set-face-background 'company-preview nil))
#+end_src

* Version control
:PROPERTIES:
:CUSTOM_ID: Version_control-51879fa8
:END:
** Built-in vc config
:PROPERTIES:
:CUSTOM_ID: Version_control-Built-in_vc_config-f2e7f46f
:END:

#+begin_src emacs-lisp :tangle (ale-minimal-config)
(use-package vc-hooks
  :straight (:type built-in)
  :config
  ;; No ask for follow symlink
  (setq vc-follow-symlinks t))
#+end_src

** Git porcelain (magit.el)
:PROPERTIES:
:CUSTOM_ID: Version_control-Git_porcelain_(magit.el)-457f1080
:END:

#+begin_src emacs-lisp
(use-package magit
  :config
  (setq magit-display-buffer-function 'magit-display-buffer-same-window-except-diff-v1)
  (setq magit-define-global-key-bindings nil)
  (setq git-commit-summary-max-length 50)
  (setq git-commit-known-pseudo-headers
        '("Signed-off-by"
          "Acked-by"
          "Modified-by"
          "Cc"
          "Suggested-by"
          "Reported-by"
          "Tested-by"
          "Reviewed-by"))
  (setq git-commit-style-convention-checks
        '(non-empty-second-line
          overlong-summary-line))
  (setq magit-diff-refine-hunk t)
  (setq magit-repository-directories
        '(("~/Code" . 1) ("~" . 1)))
  :bind (("C-M-g" . magit-status-here)
         :map magit-mode-map
         ("q" . kill-this-buffer)
         ("`" . magit-diff-show-or-scroll-up)
         :map magit-diff-section-base-map
         ("<C-return>" . magit-diff-visit-file-other-window)
         :map magit-diff-mode-map
         ("`" . scroll-up)))
#+end_src

** Hunk indicator (git-gutter.el)
:PROPERTIES:
:CUSTOM_ID: Version_control-Hunk_indicator_(git-gutter.el)-c36b82d9
:END:

#+begin_src emacs-lisp
(use-package git-gutter
  :config
  (custom-set-variables
   '(git-gutter:modified-sign "⏽")
   '(git-gutter:added-sign "⏽")
   '(git-gutter:deleted-sign "⏽")))
#+end_src

** Resolve conflict (ediff.el)
:PROPERTIES:
:CUSTOM_ID: Version_control-Resolve_conflict_(ediff.el)-5f53c33a
:END:

#+begin_src emacs-lisp
(use-package ediff
  :config
  (setq ediff-keep-variants nil)
  (setq ediff-make-buffers-readonly-at-startup nil)
  (setq ediff-merge-revisions-with-ancestor t)
  (setq ediff-show-clashes-only t)
  (setq ediff-split-window-function 'split-window-horizontally)
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
  ;; Tweak those for safer identification and removal
  (setq ediff-combination-pattern
        '("<<<<<<< ale-ediff-combine Variant A" A
          ">>>>>>> ale-ediff-combine Variant B" B
          "####### ale-ediff-combine Ancestor" Ancestor
          "======= ale-ediff-combine End"))
  (defun ale/ediff-flush-combination-pattern ()
    "Remove my custom `ediff-combination-pattern' markers.
This is a quick-and-dirty way to get rid of the markers that are
left behind by `smerge-ediff' when combining the output of two
diffs.  While this could be automated via a hook, I am not yet
sure this is a good approach."
    (interactive)
    (flush-lines ".*ale-ediff.*" (point-min) (point-max) nil)))
#+end_src

** COMMENT Forges (forge.el)
:PROPERTIES:
:CUSTOM_ID: Version_control-Forges_(forge.el)-042d4e94
:END:

#+begin_src emacs-lisp
(use-package forge)
#+end_src

* Org mode
:PROPERTIES:
:CUSTOM_ID: Org_mode-c2c13c1a
:END:
** Org (org.el)
:PROPERTIES:
:CUSTOM_ID: Org_mode-Org_(org.el)-cc3994c0
:END:

In its purest form, Org is a markup language that is similar to
Markdown: symbols are used to denote the meaning of a construct in its
context, such as what may represent a headline element or a phrase that
calls for emphasis.

What lends Org its super powers though is everything else built around
it: a rich corpus of Elisp functions that automate, link, combine,
enhance, structure, or otherwise enrich the process of using this rather
straightforward system of plain text notation.

Couched in those terms, Org is at once a distribution of well integrated
libraries and a vibrant ecosystem that keeps producing new ideas and
workflows on how to organise one's life with plain text.

This section is all about basic configurations for Org-mode which
contains several subsections as follows:

- How a =.org= file should look like
- Basic bhhaviour of headings
- Basic behaviour of source block

#+begin_src emacs-lisp
(use-package org
  :straight (:type built-in)
  :hook
  (org-mode . ale-org-font-setup)
  (org-tab-first . org-end-of-line)
  :config
  (setq org-adapt-indentation nil)
  (setq org-hide-leading-stars t)
  (setq org-startup-folded t)
  (setq org-confirm-babel-evaluate nil)
  (setq org-ellipsis " ▾")
  (setq org-hide-emphasis-markers t)
  (setq org-agenda-start-with-log-mode t)
  (setq org-log-done 'time)
  (setq org-log-into-drawer t)
  :bind
  (:map org-mode-map
        ("C-c S-l" . org-toggle-link-display)
        ("C-c C-S-l" . org-insert-last-stored-link)))
#+end_src

** Source block
:PROPERTIES:
:CUSTOM_ID: Org_mode-Source_block-3615b5bc
:END:

#+begin_src emacs-lisp
(use-package org-src
  :straight (:type built-in)
  :after-call org-mode
  :config
  (push '("conf-unix" . conf-unix) org-src-lang-modes)
  (setq org-edit-src-content-indentation 0)
  (setq org-src-window-setup 'split-window-right))

(use-package org-tempo ; this is needed as of Org 9.2
  :straight (:type built-in)
  :after-call org-mode
  :config
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("hk" . "src haskell"))
  (add-to-list 'org-structure-template-alist '("py" . "src python")))

;; Tricks for lazy loading.
;; Thanks to: https://blog.d46.us/advanced-emacs-startup/
(use-package ob-python
  :straight (:type built-in)
  :commands (org-babel-execute:python))

(use-package ob-shell
  :straight (:type built-in)
  :commands
  (org-babel-execute:shell))
#+end_src

** Bullet (org-superstar.el)
:PROPERTIES:
:CUSTOM_ID: Org_mode-Bullet_(org-superstar.el)-23c7998b
:END:

#+begin_src emacs-lisp
(use-package org-superstar
  :config
  (setq org-superstar-item-bullet-alist '((?* . ?•) (?+ . ?+) (?- . ?•)))
  (setq org-superstar-remove-leading-stars t)
  (setq org-superstar-headline-bullets-list '("◉" "○" "●" "○" "●" "○" "●"))
  :hook
  (org-mode . org-superstar-mode))
#+end_src

** Habit (org-habit.el)
:PROPERTIES:
:CUSTOM_ID: Org_mode-Habit_(org-habit.el)-d3bdb30e
:END:

#+begin_src emacs-lisp
(use-package org-habit
  :straight nil
  :config
  (add-to-list 'org-modules 'org-habit)
  (setq org-habit-graph-column 60))
#+end_src

** Wiki (org-roam.el)
:PROPERTIES:
:CUSTOM_ID: Org_mode-Wiki_(org-roam.el)-0b82aa73
:END:

#+begin_src emacs-lisp
(use-package org-roam
  :init
  (setq org-id-link-to-org-use-id t)
  (setq org-roam-v2-ack t)
  :custom
  (org-roam-directory (file-truename "~/Documents/roam"))
  (org-roam-completion-everywhere t)
  :bind
  (:map ale-org-map
        ("l" . org-roam-buffer-toggle)
        ("f" . org-roam-node-find)
        ("g" . org-roam-graph)
        ("i" . org-roam-node-insert)
        ("c" . org-roam-capture)
        ("j" . org-roam-dailies-capture-today))
  :config
  (org-roam-setup))
#+end_src

* Media
:PROPERTIES:
:CUSTOM_ID: Media-6cb9bd27
:END:
** Pdf reader (pdf-tools.el)
:PROPERTIES:
:CUSTOM_ID: Media-Pdf_reader_(pdf-tools.el)-0a9ca601
:END:

#+begin_src emacs-lisp
(use-package pdf-tools
  :after-call dired-after-readin-hook minibuffer-setup-hook
  :config
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-page)
  ;; automatically annotate highlights
  (setq pdf-annot-activate-created-annotations t)
  ;; turn off cua so copy works
  (add-hook 'pdf-view-mode-hook (lambda () (cua-mode 0)))
  ;; more fine-grained zooming
  (setq pdf-view-resize-factor 1.1)
  ;; keyboard shortcuts
  :bind
  (:map pdf-view-mode-map
  ("C-s" . isearch-forward)
  ("h" . pdf-annot-add-highlight-markup-annotation)
  ("t" . 'pdf-annot-add-text-annotation)
  ("D" . 'pdf-annot-delete)))
#+end_src

** Epub reader (nov.el)
:PROPERTIES:
:CUSTOM_ID: Media-Epub_reader_(nov.el)-6cfd5b69
:END:

#+begin_src emacs-lisp
(use-package shrface
  :after nov
  :config
  (shrface-basic)
  (shrface-trial)
  (add-to-list 'shr-external-rendering-functions
               '(span . shrface-tag-span))
  (shrface-default-keybindings) ; setup default keybindings
  (setq shrface-href-versatile t))

(use-package nov
  :init
  (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
  (add-hook 'nov-mode-hook 'ale/nov-setup)
  :config
  (advice-add 'nov-render-title :override #'ignore)
  (setq nov-shr-rendering-functions '((img . nov-render-img)
                                      (title . nov-render-title)
                                      (b . shr-tag-b)))
  (setq nov-shr-rendering-functions
        (append nov-shr-rendering-functions
                shr-external-rendering-functions))
  (defun ale/nov-setup ()
    (require 'shrface)
    (shrface-mode)))
#+end_src

* Applications
:PROPERTIES:
:CUSTOM_ID: Applications-ae0adc57
:END:
** Murl (ale-murl.el)
:PROPERTIES:
:CUSTOM_ID: Applications-Murl_(ale-murl.el)-b7d23092
:END:
*** Autoload
:PROPERTIES:
:CUSTOM_ID: Applications-Murl_(ale-murl.el)-Autoload-98ba7ff2
:END:

#+begin_src emacs-lisp :tangle (ale-init-ext-tangle)
;;; ale-murl.el -*- lexical-binding: t; -*-

(require 'json)

(defvar ale/murl-list-file (expand-file-name "~/.cache/murl/main_list.json"))

(defun ale/murl--playlist ()
  (append (json-read-file ale/murl-list-file) nil))

(defun ale/murl--get-attr (title attr)
  (cl-dolist (i (ale/murl--playlist))
    (when (string= title (cdr (assq 'title i)))
      (cl-return (cdr (assq attr i))))))

;;;###autoload
(defun ale/murl-open (&optional no-hist)
  "Select video or stream to play in mpv."
  (interactive "P")
  (unless no-hist
    (let* ((clip (condition-case nil (current-kill 0 t) (error ""))))
      (set-text-properties 0 (length clip) nil clip)
      (when-let* ((is-url (string-prefix-p "http" clip))
                  (json (shell-command-to-string (concat "murl -P 1088 json '" clip "'")))
                  (valid (string-prefix-p "{" json))
                  (obj (json-read-from-string json))
                  (playlist (ale/murl--playlist)))
        (cl-pushnew obj playlist :test 'equal)
        (with-temp-buffer
          (insert (json-encode (vconcat playlist)))
          (json-pretty-print-buffer)
          (write-region (point-min) (point-max) ale/murl-list-file)))))
  (let* ((cands-raw (mapcar (lambda (i) (cdr (assq 'title i))) (ale/murl--playlist)))
         (annotation (lambda (s) (marginalia--documentation (ale/murl--get-attr s 'url))))
         (cands (ale-minibuffer-append-metadata annotation cands-raw))
         (title (completing-read "murls: " cands))
         (sub (ale/murl--get-attr title 'sub)))
    (call-process "murl" nil 0 nil "-r" "-f" "-P" "1088" "-s" sub (ale/murl--get-attr title 'url))))

(provide 'ale-murl)
#+end_src

*** Config
:PROPERTIES:
:CUSTOM_ID: Applications-Murl_(ale-murl.el)-Config-af9c48a3
:END:

#+begin_src emacs-lisp
(bind-keys
 :map ale-utils-map
 ("m" . ale/murl-open))
#+end_src

** Dictionary (fanyi.el)
:PROPERTIES:
:CUSTOM_ID: Applications-Dictionary_(fanyi.el)-81b26b48
:END:

#+begin_src emacs-lisp
(use-package fanyi
  :bind
  (:map ale-utils-map
        ("t" . fanyi-dwim))
  :custom
  (fanyi-providers '(fanyi-etymon-provider
                     fanyi-longman-provider)))
#+end_src

