;;; init.el --- -*- lexical-binding: t -*-

(defvar ale-debug-p t)
(defvar ale-init-directory (file-name-directory user-init-file))
(defvar ale-extension-autoloads-file (concat user-emacs-directory "ale-autoload.el"))
(defvar ale-extension-directory `(,(concat ale-init-directory "core/autoload/")
                                  ,(concat ale-init-directory "lisp/")))

(let ((target-minimal (concat user-emacs-directory "ale-minimal.el"))
      (target-full (concat user-emacs-directory "ale-full.el")))
  (unless (file-exists-p target-full)
    (autoload 'ale-bootstrap-tangle (concat ale-init-directory "core/autoload/bootstrap"))
    (ale-bootstrap-tangle t))
  (unless (file-exists-p ale-extension-autoloads-file)
    (autoload 'ale-bootstrap-gen-autoloads (concat ale-init-directory "core/autoload/bootstrap"))
    (ale-bootstrap-gen-autoloads))
  (load ale-extension-autoloads-file nil t)
  (require 'core-package)
  (require 'core-editor)
  (require 'core-completion)
  (require 'core-ui)
  (require 'core-bindings)
  (load target-minimal nil t)
  (when (daemonp) (load target-full nil t)))
