(require 'ace-completing)

(defun ace/meow-append ()
  (interactive)
  (meow-tail 1)
  (meow-insert))

(defun ace/meow-append-at-end ()
  (interactive)
  (end-of-line)
  (meow-insert))

(defun ace/meow-forward-char ()
  (interactive)
  (when (< (point) (point-max))
    (forward-char)))

(defun ace/meow-backward-char ()
  (interactive)
  (let* ((pos (1- (point)))
         (char-writable (get-text-property pos 'read-only)))
    (unless char-writable
      (backward-char))))

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-colemak)
  (define-key meow-insert-state-keymap (kbd "<C-i>") #'ace/meow-backward-char)
  (define-key meow-motion-state-keymap (kbd "<escape>") #'keyboard-escape-quit)
  (define-key meow-insert-state-keymap (kbd "C-o") #'ace/meow-forward-char)
  (define-key minibuffer-local-map (kbd "<C-i>") #'ace/meow-backward-char)
  (define-key minibuffer-local-map (kbd "C-o") #'ace/meow-forward-char)
  (define-prefix-command 'meow-f-command)
  (define-prefix-command 'meow-v-command)
  (define-prefix-command 'meow-p-command)
  (define-prefix-command 'meow-u-command)
  (meow-leader-define-key
   '("?" . help-command)
   '(";" . evilnc-comment-or-uncomment-lines)
   '("`" . ace/init-edit-config)
   '("." . (lambda () (interactive) (ace/completing-file-in-user-dirs t)))
   '("e" . eval-last-sexp)
   '("k" . kill-this-buffer)
   '("i" . ace/completing-buffers-major-mode)
   '("n" . execute-extended-command)
   '("s" . save-buffer)
   '("w" . ace-select-window)
   '("z" . window-toggle-side-windows)
   '("l" . consult-line)
   '("o" . consult-outline)
   '("L" . display-line-numbers-mode)
   ;; File commands
   '("f" . meow-f-command)
   '("ff" . format-all-buffer)
   '("fu" . ace/completing-file-in-user-dirs)
   '("fr" . ace/completing-recentf)
   '("fg" . rg-dwim-current-file)
   ;; VC commands
   '("v" . meow-v-command)
   '("vv" . magit-status)
   '("vg" . git-gutter-mode)
   ;; Project commands
   '("p" . meow-p-command)
   '("pp" . project-find-file)
   '("ps" . project-switch-project)
   '("pr" . ace/rg-project-dwim)
   ;; Utils commands
   '("u" . meow-u-command)
   '("um" . ace/completing-murl))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("1" . meow-expand-1)
   '("2" . meow-expand-2)
   '("3" . meow-expand-3)
   '("4" . meow-expand-4)
   '("5" . meow-expand-5)
   '("6" . meow-expand-6)
   '("7" . meow-expand-7)
   '("8" . meow-expand-8)
   '("9" . meow-expand-9)
   '("`" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("<" . meow-beginning-of-thing)
   '(">" . meow-end-of-thing)
   '("[" . beginning-of-buffer)
   '("]" . end-of-buffer)
   '("/" . meow-visit)
   '("-" . lf)
   '("a" . ace/meow-append)
   '("A" . ace/meow-append-at-end)
   '("b" . meow-block)
   '("B" . meow-block-expand)
   '("c" . meow-change)
   '("C" . meow-change-save)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-line)
   '("E" . meow-prev-expand)
   '("f" . meow-find)
   '("F" . meow-find-expand)
   '("g" . meow-cancel)
   '("G" . meow-goto-line)
   '("h" . meow-head)
   '("H" . meow-head-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-join)
   '("k" . meow-kill)
   '("K" . meow-kill-whole-line)
   '("l" . meow-tail)
   '("L" . meow-tail-expand)
   '("m" . meow-mark-word)
   '("M" . meow-mark-symbol)
   '("n" . meow-next)
   '("N" . meow-next-expand)
   '("o" . meow-open-below)
   '("O" . meow-open-above)
   '("p" . meow-prev)
   '("P" . meow-prev-expand)
   '("q" . meow-back-word)
   '("Q" . meow-back-symbol)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-search)
   '("S" . meow-pop-search)
   '("t" . meow-till)
   '("T" . meow-till-expand)
   '("u" . undo)
   '("U" . undo-redo)
   ;; '("v" . meow-search)
   ;; '("V" . meow-pop-search)
   '("w" . meow-next-word)
   '("W" . meow-next-symbol)
   '("x" . meow-save)
   '("y" . meow-yank)
   ;; '("Y" . ace/meow-yank-eol)
   '("z" . meow-pop-selection)
   '("Z" . meow-pop-all-selection)
   '("&" . meow-query-replace)
   '("%" . meow-query-replace-regexp)))

(setq meow-visit-sanitize-completion nil)
(setq meow-esc-delay 0.001)
(setq meow-keypad-describe-delay 0.5)
(setq meow-select-on-change t)
(setq meow-cursor-type-normal 'box)
(setq meow-cursor-type-insert '(bar . 4))
(setq meow-selection-command-fallback '((meow-replace . meow-page-up)
                                        (meow-change . meow-change-char)
                                        (meow-save . meow-save-empty)
                                        (meow-kill . meow-C-k)
                                        (meow-cancel . keyboard-quit)
                                        (meow-pop . meow-pop-grab)
                                        (meow-delete . meow-C-d)))

(provide 'ace-meow)
